$env:AIALERT_RUN_WORKER_IN_PROCESS="1"
$env:AIALERT_BUS="memory"
$env:AIALERT_LLM_MODE="mock"
$env:AIALERT_LLM_LOW_CONFIDENCE="0.7"

$env:AIALERT_LLM_MODE="openai"
$env:AIALERT_LLM_ENDPOINT=""
$env:AIALERT_LLM_API_KEY=""
$env:AIALERT_LLM_MODEL="gpt-test"
